### ISSUE TITLE
Setup questions

### ISSUE THREAD

**Issue by ChaseDownDreams** [kounch/homebridge-avea-bulb#1]
First of all, I really appreciate the work you're doing and it's great that there is a plugin for the Avea Bulb. I somehow end up with some errors when i start homebridge - I guess it's my fault and not the plugin's. So I (and perhaps other people) need more details on how to setup the avea bulb:
1. To setup the accessories in config.json: Where do a get the serialnumber and the bluetooth id?
2. You say that some information is not required but what if I have more than 1 Bulb?
3. Name: Am I supposed to use the name i gave the bulb in the app?
4. Do I have to disconnect the bulb from the app?
Thanks for your time!

**Comment by kounch** [comment]
Hello

To find the Bluetooth ID, you have to resolve the MAC Bluetooth address.  For example, in Linux with the lamp turned on:
>bluetoothctl 
#scan on
…
[NEW] Device 87:B6:03:8E:5F:42 Avea_425F
…
#scan off
This would mean that the Bluetooth ID is
87b6038e5f42

If you have more than one bulb you have to set the Bluetooth ID for each one of them. If you have only one, the first one detected will be used, so no ID is needed. 

The name used for homebridge has nothing to do with the one used with the Avea App. It will be the name that shows up when the device appears in HomeKit.

The bulb only accepts one control connection, I think, at a time, and Homebridge will connect to the bulb for as long as it is running, so your app must not be running at the same time as homebridge. 

One more thing: the node process of homebridge must have permissions to scan for Bluetooth devices so, either you run it as root (i.e. with sido) or give privileges as explained here:

https://www.npmjs.com/package/noble

**Comment by ChaseDownDreams** [comment]
Okay great that fixed everything for me. Thanks for your time :)
