### ISSUE TITLE
Could not start scanning - hoobs 3 

### ISSUE THREAD

**Issue by luisfosoares** [kounch/homebridge-avea-bulb#10]
I’m using hoobs 3 into raspberry pi 4 to launch this plugin but without success. I add the name but then it won’t connect to Bluetooth , anything I should do? How to add the premissions to access Bluetooth ?
![CAC22B1B-38DF-4357-B45A-7147231A1163](https://user-images.githubusercontent.com/6531538/70381542-e85af600-1943-11ea-9e08-37a9fa741b88.png)

**Comment by kounch** [comment]
Have you followed the instructions for troubleshooting as explained in the README?

**Comment by luisfosoares** [comment]
Hello, yes I have 
But I’m not sure if I correctly did the step where i need to fill `which node` ... 

What is supposed to be placed here? Index.js in homebrige-avea-bulb node? If yes its not working anyway

**Comment by kounch** [comment]
:-)
