### ISSUE TITLE
Hoobs needs to be restarted if bulb off manually

### ISSUE THREAD

**Issue by luisfosoares** [kounch/homebridge-avea-bulb#11]
Each time by mistake I turn of manually the bulb in the physical switch and turn on again it will not be detected by the plugging and I need to restart hoobs again because it says the found bulb is not the correct one.. how to address? It’s exactly the same bulb

**Comment by kounch** [comment]
Can you attach the log for both cases?

**Comment by luisfosoares** [comment]
![70E70952-AF36-484C-B3DB-DEF32686056F](https://user-images.githubusercontent.com/6531538/70936648-04951c00-2043-11ea-8a84-e26d18306f15.jpeg)
Sorry I had forgotten

**Comment by luisfosoares** [comment]
UUID is always the same but when powered off and then on it says the device is not the one I’m looking for . Please a take in consideration than from 21:35:01 bulb worked correctly until I power cycled it at 08:02:18

**Comment by kounch** [comment]
Did you set "bluetoothid" in your configuration file?

**Comment by luisfosoares** [comment]
no , should i? is it the value ended in d45?

**Comment by kounch** [comment]
> no , should i? is it the value ended in d45?

It shouldn't have to be necessary, however since it is forgetting it, give it a try. Yes, the value to use is the one shown in your log when connecting ok:
`"bluetoothid": "e0e5cfb57d45"`

**Comment by luisfosoares** [comment]
It seems to work now that I added Id. I don’t understand why it’s not catching if Id is the same 
![5D385245-CEA7-4883-A242-3308FE62019F](https://user-images.githubusercontent.com/6531538/71129867-c3426f00-21f0-11ea-9165-4ca161d7699a.jpeg)
