### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by leon47331** [kounch/homebridge-avea-bulb#12]
![homebridge-avea-bulb-error](https://user-images.githubusercontent.com/48152632/87304193-bc74a400-c514-11ea-8ed8-c944fb71fce4.png)

Hello,
when I try to install this plugin, I get this error.
What can I do?

Have a nice day and best regards.

**Comment by kounch** [comment]
There is some problem or misconfiguration in your system, and libusb (https://libusb.info), which is an external dependency of another dependency of this project, cannot compile correctly.

If you search on internet for that error, indicating also with Linux distribution, architecture, etc. you may find a better answer.
