### ISSUE TITLE
What is wrong with the JSON-Code?

### ISSUE THREAD

**Issue by leon47331** [kounch/homebridge-avea-bulb#13]
```
"accessories": [
    {
        "accessory": "AveaBulb",
        "name": "Schreibtisch",
        "manufacturer": "Elgato",
        "model": "Avea",
        "serialnumber": "Avea_C8ED",
        "bluetoothid": "84eb1865edc8"
    }
],
```
![2021-03-20 21_15_34-Window](https://user-images.githubusercontent.com/48152632/111884340-70420380-89c1-11eb-8dee-7b2491a6bc55.png)

**Comment by kounch** [comment]
Missing enclosing curly braces enclosing everything and the last comma shouldn't be there. 


For information on how to configure homebridge, perhaps it's better to check the official documentation:
https://github.com/homebridge/homebridge/wiki/Homebridge-Config-JSON-Explained

**Comment by leon47331** [comment]
Sorry,
I just copied the code snippet from your readme.
