### ISSUE TITLE
Problem with Hoobs and Avea

### ISSUE THREAD

**Issue by stoyanland** [kounch/homebridge-avea-bulb#14]
When I install the plugin then, sudo setcap cap_net_raw+eip $(eval readlink -f `which node`), to recognise the bulb. Evrything is fine and its working but after reboot. Hoobs nevere start again, only happened with this one. Clean startup, nothing else.

**Comment by kounch** [comment]
Can’t help with some more info. Did you look at the logs?

**Comment by stoyanland** [comment]
After i reboot the pi4, just no chance to connect back, with ip or hoobs.local, nothing happened, to check the log what is the problem.

**Comment by kounch** [comment]
Then it looks like the command you used "sudo setcap cap_net_raw+eip $(eval readlink -f which node)" did break something on the system. I would use a keyboard and connect the Pi to a screen to se what happens on startup.

That command is obtained from the noble module documentation, which is the one that needs it:

https://github.com/noble/noble

Perhaps they can give you some advice there.

**Comment by kounch** [comment]
Not enough information
