### ISSUE TITLE
"npm ERR! code 128" --> trying to install the packages 

### ISSUE THREAD

**Issue by MrClou1A** [kounch/homebridge-avea-bulb#7]
**Tried the command:**
*npm install -g --unsafe-perm homebridge-avea-bulb*

**Got this message:**

> npm ERR! code 128
> npm ERR! Command failed: /usr/bin/git clone -q https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-5143b285
> npm ERR! fatal: Konnte f?hrende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-5143b285' nicht erstellen.: Keine Berechtigung
> npm ERR! 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-02-24T16_27_02_893Z-debug.log
>

**Comment by Krocko** [comment]
Try it with
'sudo chown -R $USER /usr/local && npm install -g homebridge-avea-bulb'

**Comment by MrClou1A** [comment]
> npm WARN checkPermissions Missing write access to /usr/lib/node_modules
> npm ERR! path /usr/lib/node_modules
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access
> npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
> npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
> npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'access',
> npm ERR!   path: '/usr/lib/node_modules' }
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pi/.npm/_logs/2018-02-24T16_55_20_648Z-debug.log
>

**Comment by Krocko** [comment]
You have executed this command with 'sudo'?

**Comment by MrClou1A** [comment]
yes, I did. ;-(

**Comment by Krocko** [comment]
`npm ERR! Please try running this command again as root/Administrator.`
This is really strange. 
Maybe @kounch has a solution for this.

**Comment by MrClou1A** [comment]
had a look into the listed log file, maybe it is helpful:

> 396 warn checkPermissions Missing write access to /usr/lib/node_modules
> 397 verbose stack Error: EACCES: permission denied, access '/usr/lib/node_modules'
> 398 verbose cwd /home/pi
> 399 verbose Linux 4.9.59-v7+
> 400 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-avea-bulb"
> 401 verbose node v9.6.1
> 402 verbose npm  v5.6.0
> 403 error path /usr/lib/node_modules
> 404 error code EACCES
> 405 error errno -13
> 406 error syscall access
> 407 error Error: EACCES: permission denied, access '/usr/lib/node_modules'
> 407 error  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
> 407 error   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
> 407 error   errno: -13,
> 407 error   code: 'EACCES',
> 407 error   syscall: 'access',
> 407 error   path: '/usr/lib/node_modules' }
> 408 error Please try running this command again as root/Administrator.
> 409 verbose exit [ -13, true ]
> 
>

**Comment by kounch** [comment]
What are the permissions for directory  '/usr/lib/node_modules' ?

Do  `ls -l /usr/lib` and check  node_modules permissions.

On my system they are something like
`drwxr-xr-x 16 root root     4096 feb  7 22:30 node_modules`

**Comment by MrClou1A** [comment]
`ls -l /usr/lib`

> pi@raspberrypi:~ $ ls -l /usr/lib 
total 15092
drwxr-xr-x  3 root root    4096 Nov 29 02:11 SuperCollider
drwxr-xr-x  2 root root    4096 May  3  2017 X11
drwxr-xr-x  5 root root    4096 Nov 29 01:15 apt
drwxr-xr-x 71 root root   69632 Feb 24 16:21 arm-linux-gnueabihf
drwxr-xr-x  3 root root    4096 Nov 29 01:44 aspell
drwxr-xr-x  2 root root    4096 Nov 29 01:26 avahi
drwxr-xr-x  2 root root    4096 Jul  5  2017 binfmt.d
drwxr-xr-x  2 root root    4096 Nov 29 02:07 blt2.5
drwxr-xr-x  2 root root    4096 Nov 29 01:26 bluetooth
drwxr-xr-x  4 root root    4096 Feb 24 12:20 chromium-browser
drwxr-xr-x  2 root root    4096 Nov 29 01:26 compat-ld
drwxr-xr-x  3 root root    4096 Nov 29 02:04 cups
drwxr-xr-x  2 root root    4096 Feb 24 12:18 dbus-1.0
drwxr-xr-x  2 root root    4096 Nov 29 01:44 dconf
drwxr-xr-x  3 root root    4096 Nov 29 01:28 debug
drwxr-xr-x  2 root root    4096 Nov 29 01:38 dhcpcd5
drwxr-xr-x  3 root root    4096 Nov 29 01:15 dpkg
drwxr-xr-x  4 root root    4096 Nov 29 02:13 electron
drwxr-xr-x  3 root root    4096 Nov 29 01:44 emacsen-common
drwxr-xr-x  6 root root    4096 Nov 29 02:07 erlang
drwxr-xr-x  2 root root    4096 Nov 29 01:26 file
drwxr-xr-x  3 root root    4096 Dec  4  2013 gcc
drwxr-xr-x  3 root root    4096 Nov 29 01:51 git-core
drwxr-xr-x  2 root root    4096 Nov 29 01:44 glib-networking
drwxr-xr-x  2 root root    4096 Nov 29 01:15 gnupg
drwxr-xr-x  2 root root    4096 Nov 29 01:15 gnupg2
drwxr-xr-x  2 root root    4096 Nov 29 01:26 gold-ld
drwxr-xr-x  4 root root    4096 Nov 29 01:15 groff
drwxr-xr-x  2 root root    4096 Nov 29 01:46 gvfs
drwxr-xr-x  2 root root    4096 Nov 29 01:44 ispell
drwxr-xr-x  3 root root    4096 Nov 29 02:06 jvm
drwxr-xr-x  3 root root    4096 Jul  5  2017 kernel
drwxr-xr-x  3 root root    4096 May 18  2016 klibc
drwxr-xr-x  2 root root    4096 Nov 29 02:03 lapack
drwxr-xr-x  2 root root    4096 Nov 29 01:26 ldscripts
-rw-r--r--  1 root root 1115072 Dec  1  2015 libBLT.2.5.so.8.6
-rw-r--r--  1 root root  255496 Dec  1  2015 libBLTlite.2.5.so.8.6
lrwxrwxrwx  1 root root      16 Jul  4  2017 libRTIMULib.so -> libRTIMULib.so.7
lrwxrwxrwx  1 root root      20 Jul  4  2017 libRTIMULib.so.7 -> libRTIMULib.so.7.2.1
-rw-r--r--  1 root root  151088 Jul  4  2017 libRTIMULib.so.7.2.1
drwxr-xr-x  2 root root    4096 Nov 29 02:03 libblas
lrwxrwxrwx  1 root root      30 Nov 29 02:04 libblas.so.3 -> /etc/alternatives/libblas.so.3
-rw-r--r--  1 root root 1061368 Feb  6  2016 libcmumps_seq-4.10.0.so
lrwxrwxrwx  1 root root      20 Apr 26  2012 libcompface.so.1 -> libcompface.so.1.0.0
-rw-r--r--  1 root root   20344 Apr 26  2012 libcompface.so.1.0.0
-rw-r--r--  1 root root 1049064 Feb  6  2016 libdmumps_seq-4.10.0.so
drwxr-xr-x  2 root root    4096 Nov 29 01:46 libgksu
lrwxrwxrwx  1 root root      17 Sep 26  2016 libgksu2.so.0 -> libgksu2.so.0.0.2
-rw-r--r--  1 root root   51656 Sep 26  2016 libgksu2.so.0.0.2
lrwxrwxrwx  1 root root      24 Mar  4  2017 libgnome-menu-3.so.0 -> libgnome-menu-3.so.0.0.1
-rw-r--r--  1 root root   92340 Mar  4  2017 libgnome-menu-3.so.0.0.1
lrwxrwxrwx  1 root root      16 Nov 11  2016 libident.so.0 -> libident.so.0.22
-rw-r--r--  1 root root    7976 Nov 11  2016 libident.so.0.22
lrwxrwxrwx  1 root root      17 Sep 11  2015 libipopt.so.1 -> libipopt.so.1.9.9
-rw-r--r--  1 root root 2317880 Sep 11  2015 libipopt.so.1.9.9
lrwxrwxrwx  1 root root      21 Nov 14  2015 libkeybinder.so.0 -> libkeybinder.so.0.1.0
-rw-r--r--  1 root root    9588 Nov 14  2015 libkeybinder.so.0.1.0
lrwxrwxrwx  1 root root      32 Nov 29 02:05 liblapack.so.3 -> /etc/alternatives/liblapack.so.3
lrwxrwxrwx  1 root root      19 Jan  4  2017 liblilv-0.so.0 -> liblilv-0.so.0.24.2
-rw-r--r--  1 root root   75064 Jan  4  2017 liblilv-0.so.0.24.2
-rw-r--r--  1 root root   25600 Feb  6  2016 libmpiseq_seq-4.10.0.so
-rw-r--r--  1 root root  256624 Feb  6  2016 libmumps_common_seq-4.10.0.so
-rw-r--r--  1 root root  246952 Sep 11 16:44 libpigpio.so
-rw-r--r--  1 root root   73824 Sep 11 16:44 libpigpiod_if.so
-rw-r--r--  1 root root   86112 Sep 11 16:44 libpigpiod_if2.so
lrwxrwxrwx  1 root root      24 Feb 16  2017 libpigpioultrasonic.so -> libpigpioultrasonic.so.1
-rw-r--r--  1 root root    8828 Apr 25  2016 libpigpioultrasonic.so.1
lrwxrwxrwx  1 root root      18 Aug 15  2015 libpisock.so.9 -> libpisock.so.9.0.2
-rw-r--r--  1 root root  204468 Aug 15  2015 libpisock.so.9.0.2
-rw-r--r--  1 root root   75728 Feb  6  2016 libpord_seq-4.10.0.so
lrwxrwxrwx  1 root root      32 Aug  2  2016 libpyglib-2.0-python2.7.so.0 -> libpyglib-2.0-python2.7.so.0.0.0
-rw-r--r--  1 root root   11684 Aug  2  2016 libpyglib-2.0-python2.7.so.0.0.0
lrwxrwxrwx  1 root root      21 Jan  9  2017 libpypy-c.so -> pypy/bin/libpypy-c.so
lrwxrwxrwx  1 root root      26 Nov 14  2016 libqt5scintilla2.so.12 -> libqt5scintilla2.so.12.0.2
lrwxrwxrwx  1 root root      26 Nov 14  2016 libqt5scintilla2.so.12.0 -> libqt5scintilla2.so.12.0.2
-rw-r--r--  1 root root 3262260 Nov 14  2016 libqt5scintilla2.so.12.0.2
lrwxrwxrwx  1 root root      19 Sep  5  2016 libqwt-qt5.so.6 -> libqwt-qt5.so.6.1.2
lrwxrwxrwx  1 root root      19 Sep  5  2016 libqwt-qt5.so.6.1 -> libqwt-qt5.so.6.1.2
-rw-r--r--  1 root root 1116892 Sep  5  2016 libqwt-qt5.so.6.1.2
drwxr-xr-x  5 root root    4096 Feb 24 12:17 libreoffice
lrwxrwxrwx  1 root root      19 Nov 16  2016 libscsynth.so.1 -> libscsynth.so.1.0.0
-rw-r--r--  1 root root  423392 Nov 16  2016 libscsynth.so.1.0.0
lrwxrwxrwx  1 root root      20 May 24  2012 libsigc-1.2.so.5 -> libsigc-1.2.so.5.0.7
-rw-r--r--  1 root root   23724 May 24  2012 libsigc-1.2.so.5.0.7
-rw-r--r--  1 root root 1045928 Feb  6  2016 libsmumps_seq-4.10.0.so
lrwxrwxrwx  1 root root      14 Apr  3  2017 libsrtp.so.0 -> libsrtp.so.0.0
-rw-r--r--  1 root root   90620 Apr  3  2017 libsrtp.so.0.0
-rw-r--r--  1 root root   16500 Aug 29  2016 libsupp.a
lrwxrwxrwx  1 root root      24 Sep 20  2014 libunique-1.0.so.0 -> libunique-1.0.so.0.100.6
-rw-r--r--  1 root root   43064 Sep 20  2014 libunique-1.0.so.0.100.6
lrwxrwxrwx  1 root root      18 Jun 25  2012 libvte.so.9 -> libvte.so.9.2800.2
-rw-r--r--  1 root root  570448 Jun 25  2012 libvte.so.9.2800.2
drwxr-xr-x  2 root root    4096 Nov 29 01:46 libvte9
lrwxrwxrwx  1 root root      19 Nov 29 02:13 libwiringPi.so -> libwiringPi.so.2.44
-rwxr-xr-x  1 root root   69844 Oct 31 13:51 libwiringPi.so.2.44
lrwxrwxrwx  1 root root      22 Nov 29 02:13 libwiringPiDev.so -> libwiringPiDev.so.2.44
-rwxr-xr-x  1 root root   28180 Oct 31 13:51 libwiringPiDev.so.2.44
-rw-r--r--  1 root root 1065452 Feb  6  2016 libzmumps_seq-4.10.0.so
drwxr-xr-x  3 root root    4096 Feb 24 10:13 locale
drwxr-xr-x  2 root root    4096 Nov 29 02:03 lp_solve
drwxr-xr-x  2 root root    4096 Nov 29 01:15 man-db
drwxr-xr-x  2 root root    4096 Nov 29 01:46 menu-cache
drwxr-xr-x  3 root root    4096 Nov 29 01:25 mime
drwxr-xr-x  2 root root    4096 Jul  5  2017 modules-load.d
drwxr-xr-x  9 root root    4096 Feb 24 18:53 node_modules
drwxr-xr-x  2 root root    4096 Feb 24 12:20 openssh
-rw-r--r--  1 root root     278 Dec 13 23:18 os-release
drwxr-xr-x  2 root root    4096 Nov 29 02:03 packagekit
drwxr-xr-x  2 root root    4096 Jul 20  2011 perl5
-rw-r--r--  1 root root      20 May  7  2016 pkg-config.multiarch
drwxr-xr-x  2 root root    4096 May  7  2016 pkgconfig
drwxr-xr-x  3 root root    4096 Nov 29 01:38 pm-utils
drwxr-xr-x  2 root root    4096 Nov 29 01:47 policykit-1
drwxr-xr-x  8 root root    4096 Nov 29 02:07 pypy
drwxr-xr-x  4 root root    4096 Nov 29 02:10 pyshared
drwxr-xr-x  3 root root    4096 Nov 29 02:10 python2.6
drwxr-xr-x 28 root root   24576 Feb 24 12:30 python2.7
drwxr-xr-x  3 root root    4096 May 21  2017 python3
drwxr-xr-x 34 root root    4096 Nov 29 02:10 python3.5
drwxr-xr-x  2 root root    4096 Feb 24 12:24 raspberrypi-sys-mods
drwxr-xr-x  2 root root    4096 Feb 24 10:15 raspi-config
drwxr-xr-x  5 root root    4096 Nov 29 02:08 ruby
drwxr-xr-x  2 root root    4096 Mar 19  2017 sasl2
drwxr-xr-x  3 root root    4096 Nov 29 02:09 scratch
drwxr-xr-x 14 root root    4096 Nov 29 02:13 scratch2
lrwxrwxrwx  1 root root      19 Nov 18 09:37 sftp-server -> openssh/sftp-server
drwxr-xr-x  4 root root    4096 Nov 29 02:09 squeak
drwxr-xr-x  3 root root    4096 Nov 29 01:27 ssl
drwxr-xr-x  2 root root    4096 Nov 29 01:28 sudo
drwxr-xr-x  8 root root    4096 Nov 29 02:04 systemd
drwxr-xr-x  2 root root    4096 Oct 30  2016 tar
drwxr-xr-x  4 root root    4096 Nov 29 01:15 tasksel
drwxr-xr-x  2 root root    4096 Feb 24 12:20 tc
drwxr-xr-x  3 root root    4096 Nov 29 02:07 tcltk
drwxr-xr-x  2 root root    4096 Nov 29 01:47 thunar-archive-plugin
drwxr-xr-x  3 root root    4096 Nov 29 02:04 timidity
drwxr-xr-x  2 root root    4096 Feb 24 12:20 tmpfiles.d
drwxr-xr-x  2 root root    4096 Nov 29 01:46 udisks2
drwxr-xr-x  2 root root    4096 Nov 29 01:25 valgrind
drwxr-xr-x  2 root root    4096 Feb 24 12:25 vnc
drwxr-xr-x  3 root root    4096 Nov 29 01:47 xorg

>

**Comment by MrClou1A** [comment]
> pi@raspberrypi:~ $ ls -l /usr/lib/node_modules/
total 24
drwxr-xr-x 6 root root 4096 Feb 24 13:32 homebridge
drwxr-xr-x 4 root root 4096 Feb 24 18:53 homebridge-avea-bulb
drwxr-xr-x 2 root root 4096 Feb 24 15:50 homebridge-delay-switch
drwxr-xr-x 4 root root 4096 Feb 24 14:51 homebridge-tahoma
drwxr-xr-x 3 root root 4096 Feb 24 15:35 homebridge-weather-station-extended
drwxr-xr-x 9 root root 4096 Feb 24 13:17 npm

>

**Comment by kounch** [comment]
Permissions seem to be ok.

I would try to make sure that your are using the latest version of your system and if after that it still doesn't work, reinstall nodejs and npm, since it looks like they are broken.

Note: I have redacted your comment to leave the relevant parts, and protect your privacy

**Comment by MrClou1A** [comment]
> Note: I have redacted your comment to leave the relevant parts, and protect your privacy

big thanks. will try to re-install them!

**Comment by kounch** [comment]
If you don't want to have your modules managed only by root, you can try to reconfigure your node installation to use a different location, as explained here:

https://github.com/npm/npm/issues/8165#issuecomment-264002075

But then you would have to reinstall all your modules there, and i am not sure if this would really resolve your problem. Anyway, i leave here the information in case it is useful for someone else too.

**Comment by MrClou1A** [comment]
> Does removing homebridge-avea-bulb work? (with the commandnpm uninstall -g homebridge-avea-bulb)
NOPE ;-)

**Comment by MrClou1A** [comment]
> And after, if it still doesn't work, try reinstalling nodejs and npm, since it looks like they are broken.

I did. Downgraded to Version 8.x but them my homebridge failed to start. Now I'm back on Version 9.x with new installed packages, Homebridge works again, but installation for the aves-bulb still fails ;-(

**Comment by kounch** [comment]
:-(

And I assume that installing other modules works fine, doesn’t it?

**Comment by MrClou1A** [comment]
I'm sorry to say, but yes.

**Comment by kounch** [comment]
Since uninstall also doesn’t work I would suggest to mov the homebridge-avea-bulb directory to another location, and then try to uninstall and install again

It is weird

**Comment by MrClou1A** [comment]
by the way: I tried to install your second VERY NICE project "homebridge-cmdtrigger", but got the same error as on installation of this project: 

> root@raspberrypi:/home/pi# npm install -g https://github.com/hallos/homebridge-cmdtrigger
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/hallos/homebridge-cmdtrigger.git /root/.npm/_cacache/tmp/git-clone-70e351af
npm ERR! fatal: Konnte f?hrende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-70e351af' nicht erstellen.: Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T16_12_06_502Z-debug.log

>

**Comment by MrClou1A** [comment]
OH BOY - you made my day!

**Comment by kounch** [comment]
:-)

I will add this information in the installing instructions. 

Closed
